### PR TITLE
Fix for parsing mime email

### LINKED ISSUE #5: Parsing emails received in receiver.js

### PR DESCRIPTION
**Pull request by meets2tarun**
Fixes #5

### CODE REVIEW

**Comment by accakks** [comment]
Hey so we're using mailparser? What about what rushabh suggested? Did you check that out?

**Comment by meets2tarun** [comment]
This is `mail-parser`, and `mailparser` is different.
And what rushabh told doesn't work out.

**Comment by accakks** [comment]
oh, okay, so this is pip.

**Comment by inishchith** [comment]
@meets2tarun any updates ?

**Comment by meets2tarun** [comment]
@email-frappejs/email-team 
The script is working, the problem I'm searching for is to straight forward getting the .json file without any intermediate text file.
That is the reason of the delay. I'm working on the same.

**Comment by inishchith** [comment]
@meets2tarun Cool . Update this when done .

**Comment by meets2tarun** [comment]
Closed due to use of the external dependencies.

**Pull request closed without merging**
